//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmetic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class st1_Rassadin_CosmeticEntities1 : DbContext
    {
        private static st1_Rassadin_CosmeticEntities1 _context;
        public st1_Rassadin_CosmeticEntities1()
            : base("name=st1_Rassadin_CosmeticEntities1")
        {
        }
        public static st1_Rassadin_CosmeticEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new st1_Rassadin_CosmeticEntities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderServices> OrderServices { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
